#pragma once

#ifndef FABRICA_RUNTIME_CONFIG
#define FABRICA_RUNTIME_CONFIG DEV
#endif

#define FABRICA_RUNTIME_PRIVATE_DEFINITION_DEV() 0
#define FABRICA_RUNTIME_PRIVATE_DEFINITION_SHIP() 1
#define FABRICA_RUNTIME_XSMASH(X, Y) X##Y()
#define FABRICA_RUNTIME_SMASH(X, Y) FABRICA_RUNTIME_XSMASH(X, Y)
#define FABRICA_RUNTIME(X)                         \
  (FABRICA_RUNTIME_PRIVATE_DEFINITION_##X() ==     \
   FABRICA_RUNTIME_SMASH(FABRICA_RUNTIME_PRIVATE_DEFINITION_, FABRICA_RUNTIME_CONFIG))

#define FABRICA_PLATFORM_PRIVATE_WINDOWS() 0
#define FABRICA_PLATFORM_PRIVATE_LINUX() 0
#define FABRICA_PLATFORM_PRIVATE_DESKTOP() 0
#define FABRICA_PLATFORM(X) FABRICA_PLATFORM_PRIVATE_##X()

#if defined(_WIN32) || defined(_WIN64)
#undef FABRICA_PLATFORM_PRIVATE_WINDOWS
#define FABRICA_PLATFORM_PRIVATE_WINDOWS() 1
#elif defined(__linux__)
#undef FABRICA_PLATFORM_PRIVATE_LINUX
#define FABRICA_PLATFORM_PRIVATE_LINUX() 1
#endif

#if FABRICA_PLATFORM(WINDOWS) || FABRICA_PLATFORM(LINUX)
#undef FABRICA_PLATFORM_PRIVATE_DESKTOP
#define FABRICA_PLATFORM_PRIVATE_DESKTOP() 1
#endif

#define FABRICA_THREADS_PRIVATE_STDLIB() 0
#define FABRICA_THREADS_PRIVATE_CUSTOM() 0
#define FABRICA_THREADS(X) FABRICA_THREADS_PRIVATE_##X()

#undef FABRICA_THREADS_PRIVATE_STDLIB
#define FABRICA_THREADS_PRIVATE_STDLIB() 1

#if !defined(FABRICA_DEBUG_BUILD) && !defined(FABRICA_SHIP_BUILD)
#if FABRICA_RUNTIME(DEV)
#define FABRICA_DEBUG_BUILD 1
#else
#define FABRICA_SHIP_BUILD 1
#endif
#endif

#if !defined(FABRICA_LOG_MIN_LEVEL)
#define FABRICA_LOG_MIN_LEVEL 0
#endif

#if !defined(FABRICA_PAL_VERBOSE_LOG)
#define FABRICA_PAL_VERBOSE_LOG 0
#endif

#if !defined(FABRICA_WINDOW_VERBOSE_LOG)
#define FABRICA_WINDOW_VERBOSE_LOG 0
#endif

#if !defined(FABRICA_ASYNC_VERBOSE_LOG)
#define FABRICA_ASYNC_VERBOSE_LOG 0
#endif

#if !defined(FABRICA_JOBS_VERBOSE_LOG)
#define FABRICA_JOBS_VERBOSE_LOG 0
#endif

#if !defined(FABRICA_ASSETS_VERBOSE_LOG)
#define FABRICA_ASSETS_VERBOSE_LOG 0
#endif

#if !defined(FABRICA_MEMORY_VERBOSE_LOG)
#define FABRICA_MEMORY_VERBOSE_LOG 0
#endif

#if !defined(FABRICA_MEMORY_TRACKING)
#define FABRICA_MEMORY_TRACKING 0
#endif

